// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sentinel/v1/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionEvent struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	TenantId            string                   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DecisionId          string                   `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Timestamp           *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ContextFeatures     map[string]*FeatureValue `protobuf:"bytes,4,rep,name=context_features,json=contextFeatures,proto3" json:"context_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Action              string                   `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Propensity          float64                  `protobuf:"fixed64,6,opt,name=propensity,proto3" json:"propensity,omitempty"`
	ActionProbabilities []*ActionProbability     `protobuf:"bytes,7,rep,name=action_probabilities,json=actionProbabilities,proto3" json:"action_probabilities,omitempty"`
	PolicyId            string                   `protobuf:"bytes,8,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ModelSnapshotId     string                   `protobuf:"bytes,9,opt,name=model_snapshot_id,json=modelSnapshotId,proto3" json:"model_snapshot_id,omitempty"`
	ExperimentId        string                   `protobuf:"bytes,10,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Metadata            map[string]string        `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DecisionEvent) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DecisionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DecisionEvent) GetContextFeatures() map[string]*FeatureValue {
	if x != nil {
		return x.ContextFeatures
	}
	return nil
}

func (x *DecisionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DecisionEvent) GetPropensity() float64 {
	if x != nil {
		return x.Propensity
	}
	return 0
}

func (x *DecisionEvent) GetActionProbabilities() []*ActionProbability {
	if x != nil {
		return x.ActionProbabilities
	}
	return nil
}

func (x *DecisionEvent) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DecisionEvent) GetModelSnapshotId() string {
	if x != nil {
		return x.ModelSnapshotId
	}
	return ""
}

func (x *DecisionEvent) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *DecisionEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ActionProbability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Probability   float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionProbability) Reset() {
	*x = ActionProbability{}
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionProbability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProbability) ProtoMessage() {}

func (x *ActionProbability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProbability.ProtoReflect.Descriptor instead.
func (*ActionProbability) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ActionProbability) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionProbability) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type FeatureValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FeatureValue_Numeric
	//	*FeatureValue_Categorical
	//	*FeatureValue_NumericVector
	//	*FeatureValue_EmbeddingName
	Kind          isFeatureValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureValue) Reset() {
	*x = FeatureValue{}
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureValue) ProtoMessage() {}

func (x *FeatureValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureValue.ProtoReflect.Descriptor instead.
func (*FeatureValue) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureValue) GetKind() isFeatureValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FeatureValue) GetNumeric() float64 {
	if x != nil {
		if x, ok := x.Kind.(*FeatureValue_Numeric); ok {
			return x.Numeric
		}
	}
	return 0
}

func (x *FeatureValue) GetCategorical() string {
	if x != nil {
		if x, ok := x.Kind.(*FeatureValue_Categorical); ok {
			return x.Categorical
		}
	}
	return ""
}

func (x *FeatureValue) GetNumericVector() *NumericVector {
	if x != nil {
		if x, ok := x.Kind.(*FeatureValue_NumericVector); ok {
			return x.NumericVector
		}
	}
	return nil
}

func (x *FeatureValue) GetEmbeddingName() string {
	if x != nil {
		if x, ok := x.Kind.(*FeatureValue_EmbeddingName); ok {
			return x.EmbeddingName
		}
	}
	return ""
}

type isFeatureValue_Kind interface {
	isFeatureValue_Kind()
}

type FeatureValue_Numeric struct {
	Numeric float64 `protobuf:"fixed64,1,opt,name=numeric,proto3,oneof"`
}

type FeatureValue_Categorical struct {
	Categorical string `protobuf:"bytes,2,opt,name=categorical,proto3,oneof"`
}

type FeatureValue_NumericVector struct {
	NumericVector *NumericVector `protobuf:"bytes,3,opt,name=numeric_vector,json=numericVector,proto3,oneof"`
}

type FeatureValue_EmbeddingName struct {
	EmbeddingName string `protobuf:"bytes,4,opt,name=embedding_name,json=embeddingName,proto3,oneof"`
}

func (*FeatureValue_Numeric) isFeatureValue_Kind() {}

func (*FeatureValue_Categorical) isFeatureValue_Kind() {}

func (*FeatureValue_NumericVector) isFeatureValue_Kind() {}

func (*FeatureValue_EmbeddingName) isFeatureValue_Kind() {}

type NumericVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericVector) Reset() {
	*x = NumericVector{}
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericVector) ProtoMessage() {}

func (x *NumericVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericVector.ProtoReflect.Descriptor instead.
func (*NumericVector) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *NumericVector) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_sentinel_v1_events_proto protoreflect.FileDescriptor

const file_proto_sentinel_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/sentinel/v1/events.proto\x12\x12sentinel.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x05\n" +
	"\rDecisionEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12a\n" +
	"\x10context_features\x18\x04 \x03(\v26.sentinel.events.v1.DecisionEvent.ContextFeaturesEntryR\x0fcontextFeatures\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"propensity\x18\x06 \x01(\x01R\n" +
	"propensity\x12X\n" +
	"\x14action_probabilities\x18\a \x03(\v2%.sentinel.events.v1.ActionProbabilityR\x13actionProbabilities\x12\x1b\n" +
	"\tpolicy_id\x18\b \x01(\tR\bpolicyId\x12*\n" +
	"\x11model_snapshot_id\x18\t \x01(\tR\x0fmodelSnapshotId\x12#\n" +
	"\rexperiment_id\x18\n" +
	" \x01(\tR\fexperimentId\x12K\n" +
	"\bmetadata\x18\v \x03(\v2/.sentinel.events.v1.DecisionEvent.MetadataEntryR\bmetadata\x1ad\n" +
	"\x14ContextFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sentinel.events.v1.FeatureValueR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x11ActionProbability\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\"\xcb\x01\n" +
	"\fFeatureValue\x12\x1a\n" +
	"\anumeric\x18\x01 \x01(\x01H\x00R\anumeric\x12\"\n" +
	"\vcategorical\x18\x02 \x01(\tH\x00R\vcategorical\x12J\n" +
	"\x0enumeric_vector\x18\x03 \x01(\v2!.sentinel.events.v1.NumericVectorH\x00R\rnumericVector\x12'\n" +
	"\x0eembedding_name\x18\x04 \x01(\tH\x00R\rembeddingNameB\x06\n" +
	"\x04kind\"'\n" +
	"\rNumericVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06valuesB#Z!sentinel/proto/sentinel/v1/eventsb\x06proto3"

var (
	file_proto_sentinel_v1_events_proto_rawDescOnce sync.Once
	file_proto_sentinel_v1_events_proto_rawDescData []byte
)

func file_proto_sentinel_v1_events_proto_rawDescGZIP() []byte {
	file_proto_sentinel_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_v1_events_proto_rawDesc), len(file_proto_sentinel_v1_events_proto_rawDesc)))
	})
	return file_proto_sentinel_v1_events_proto_rawDescData
}

var file_proto_sentinel_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sentinel_v1_events_proto_goTypes = []any{
	(*DecisionEvent)(nil),         // 0: sentinel.events.v1.DecisionEvent
	(*ActionProbability)(nil),     // 1: sentinel.events.v1.ActionProbability
	(*FeatureValue)(nil),          // 2: sentinel.events.v1.FeatureValue
	(*NumericVector)(nil),         // 3: sentinel.events.v1.NumericVector
	nil,                           // 4: sentinel.events.v1.DecisionEvent.ContextFeaturesEntry
	nil,                           // 5: sentinel.events.v1.DecisionEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_sentinel_v1_events_proto_depIdxs = []int32{
	6, // 0: sentinel.events.v1.DecisionEvent.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: sentinel.events.v1.DecisionEvent.context_features:type_name -> sentinel.events.v1.DecisionEvent.ContextFeaturesEntry
	1, // 2: sentinel.events.v1.DecisionEvent.action_probabilities:type_name -> sentinel.events.v1.ActionProbability
	5, // 3: sentinel.events.v1.DecisionEvent.metadata:type_name -> sentinel.events.v1.DecisionEvent.MetadataEntry
	3, // 4: sentinel.events.v1.FeatureValue.numeric_vector:type_name -> sentinel.events.v1.NumericVector
	2, // 5: sentinel.events.v1.DecisionEvent.ContextFeaturesEntry.value:type_name -> sentinel.events.v1.FeatureValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_sentinel_v1_events_proto_init() }
func file_proto_sentinel_v1_events_proto_init() {
	if File_proto_sentinel_v1_events_proto != nil {
		return
	}
	file_proto_sentinel_v1_events_proto_msgTypes[2].OneofWrappers = []any{
		(*FeatureValue_Numeric)(nil),
		(*FeatureValue_Categorical)(nil),
		(*FeatureValue_NumericVector)(nil),
		(*FeatureValue_EmbeddingName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_v1_events_proto_rawDesc), len(file_proto_sentinel_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sentinel_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_sentinel_v1_events_proto_msgTypes,
	}.Build()
	File_proto_sentinel_v1_events_proto = out.File
	file_proto_sentinel_v1_events_proto_goTypes = nil
	file_proto_sentinel_v1_events_proto_depIdxs = nil
}
