import { Timestamp } from "firebase/firestore";


export interface SystemLog {
  id: string;
  timestamp: number;
  level: 'INFO' | 'WARN' | 'ERROR' | 'NEURAL' | 'CRITICAL';
  source: string;
  message: string;
  traceId?: string;
}

export interface ExperienceTuple {
  state: number[];
  action: number;
  reward: number;
  nextState: number[];
  done: boolean;
}

export interface ReplayBatch {
  timestamp: number;
  experiences: ExperienceTuple[];
}

export interface DreamLog {
  timestamp: number;
  gain: number;
  steps: number;
  summary: string;
  narrative?: string;
  validationLoss?: number;
  cqlPenalty?: number;
  policyLoss?: number;
}

export interface WorldModelWeightsDoc {
  updatedAt: number;
  stateDim: number;
  actionDim: number;
  latentDim: number;
  embedDim: number;
  topology: string;
  weights: number[][];
}

export interface SerializedDQN {
  layers: { weights: string; biases: string; }[];
  inputSize: number;
  outputSize: number;
}

export interface OptionMetadata {
  id: string;
  name: string;
  description: string;
  actionSpace: string[];
  timesActivated: number;
  averageDuration: number;
  lastUsed: number;
}

export interface SerializedPolicyNet {
  weights: string;
  updatedAt: number;
  inputSize: number;
  outputSize: number;
}

export interface FederatedModelUpdate {
  userId: string;
  round: number;
  modelType: 'vrssm' | 'policy' | 'concepts';
  weights: any[];
  sampleSize: number;
  timestamp: any;
}

export interface PrivacyMetrics {
  epsilon: number;
  delta: number;
  noiseLevel: number;
}

export interface FederatedGlobalModel {
  round: number;
  weights: any[];
  updatedAt: number;
}

export interface DebateAgentWeights {
  policyNetwork: SerializedPolicyNet;
  preferences: { mu: number[]; invCov: number[][] };
  metaParams: { learningRate: number; temperature: number };
}

export interface DebateTransition {
  state: number[];
  move: number;
  nextState: number[];
  reward: number;
  agentId: string;
  topic: string;
  timestamp: any;
}

export interface SystemHealthVector {
  memoryUsageRatio: number;
  cpuLoad: number;
  activeWorkerCount: number;
  pendingTaskQueueSize: number;
  firestoreReadErrors: number;
  firestoreWriteErrors: number;
  geminiLatencyMs: number;
  unhandledErrors: number;
  dreamCycleFailureRate: number;
  timestamp: number;
}

export enum MaintenanceActionType {
  NOOP = 'NOOP',
  RESTART_IDLE_WORKER = 'RESTART_IDLE_WORKER',
  CLEAR_MODEL_CACHE = 'CLEAR_MODEL_CACHE',
  REDUCE_BATCH_SIZE = 'REDUCE_BATCH_SIZE',
  INCREASE_RETRY_DELAY = 'INCREASE_RETRY_DELAY',
  FLUSH_LOGS = 'FLUSH_LOGS',
  ROLLBACK_MODEL = 'ROLLBACK_MODEL',
  TRIGGER_GARBAGE_COLLECTION = 'TRIGGER_GARBAGE_COLLECTION',
  ALERT_USER = 'ALERT_USER',
  RUN_DIAGNOSTIC = 'RUN_DIAGNOSTIC'
}

export interface MaintenanceAction {
  type: MaintenanceActionType;
  requiresConfirmation: boolean;
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  description: string;
}

export interface VADVector {
  valence: number;  // -1 to 1
  arousal: number;  // -1 to 1
  dominance: number; // -1 to 1
}

export interface EmotionSnapshot {
  userId: string;
  vad: VADVector;
  timestamp: number;
}

export interface CircadianModel {
  userId: string;
  valenceCoeffs: number[];
  arousalCoeffs: number[];
  dominanceCoeffs: number[];
  updatedAt: number;
}

export interface RLWeightsDoc {
  updatedAt: number;
  topLevel: SerializedDQN;
  options: Record<string, SerializedDQN>;
  icm: {
    featureNet: SerializedDQN;
    forwardNet: SerializedDQN;
    inverseNet: SerializedDQN;
  };
  hyperparams: {
    epsilon: number;
    learningRate: number;
    discountFactor: number;
  };
}

export interface MemoryNode {
  id: string;
  content: string;            // raw text
  summary: string;            // semantic gist (generated by Gemini)
  embedding: number[];        // vector from Gemini/RAG
  tags: string[];
  strength: number;           // 0-1
  state: 'ephemeral' | 'shortTerm' | 'longTerm' | 'core' | 'wisdom' | 'forgotten' | 'transformed';
  createdAt: Timestamp;
  lastAccessed: Timestamp;
  accessCount: number;
  consolidatedAt?: Timestamp;
  decayRate: number;          // base decay per hour
  linkedMemories: string[];   // IDs of related nodes
  parentWisdom?: string;      // ID of wisdom node that absorbed this
  userId: string;
}

export interface WisdomNode {
  id: string;
  insight: string;            // the distilled wisdom
  sourceMemoryIds: string[];  // IDs of the core memories that created this
  strength: number;
  createdAt: Timestamp;
  lastAccessed: Timestamp;
  userId: string;
}

export interface ERDEntity {
  name: string;
  type: string;
  canonical: string;
  relations: string[];
}

export interface ERDResult {
  entities: ERDEntity[];
}

export interface Episode {
  id: string;
  timestamp: number;
  trigger: string;
  context: Record<string, any>;
  actionsTaken: string[];
  outcome: 'success' | 'failure' | 'neutral' | 'partial';
  reward: number;
  emotionalState?: VADVector;
  embedding?: number[];
}

export interface SemanticEntry {
  id: string;
  concept: string;
  definition: string;
  associations: string[];
  strength: number;
  lastAccessed: number;
  embedding?: number[];
}

export interface Memory {
  episodic: Episode[];
  semantic: SemanticEntry[];
}

export interface SkillCard {
  id: string;
  name: string;
  description: string;
  preconditions: Record<string, any>;
  executionLogic: string; // Could be a function reference or script
  successRate: number;
  useCount: number;
  lastUsed: number;
}

export interface Identity {
  coreValues: string[];
  personalityTraits: Record<string, number>; // e.g., Openness: 0.8
  currentGoals: string[];
  activeDirectives: string[];
}

export interface AutonomyAction {
  id: string;
  timestamp: number;
  type: string;
  target?: string;
  parameters: Record<string, any>;
  reasoning: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
}
