// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sentinel/v1/decision_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	events "sentinel/proto/sentinel/v1/events"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActionRequest struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	TenantId        string                          `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientRequestId string                          `protobuf:"bytes,2,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	Context         map[string]*events.FeatureValue `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options         map[string]string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActionRequest) Reset() {
	*x = GetActionRequest{}
	mi := &file_proto_sentinel_v1_decision_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequest) ProtoMessage() {}

func (x *GetActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_decision_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_decision_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetActionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetActionRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *GetActionRequest) GetContext() map[string]*events.FeatureValue {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetActionRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetActionResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	DecisionId    string                          `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	TenantId      string                          `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Action        string                          `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Propensity    float64                         `protobuf:"fixed64,4,opt,name=propensity,proto3" json:"propensity,omitempty"`
	PolicyId      string                          `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ContextUsed   map[string]*events.FeatureValue `protobuf:"bytes,6,rep,name=context_used,json=contextUsed,proto3" json:"context_used,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionResponse) Reset() {
	*x = GetActionResponse{}
	mi := &file_proto_sentinel_v1_decision_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionResponse) ProtoMessage() {}

func (x *GetActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_v1_decision_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionResponse.ProtoReflect.Descriptor instead.
func (*GetActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_v1_decision_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *GetActionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetActionResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetActionResponse) GetPropensity() float64 {
	if x != nil {
		return x.Propensity
	}
	return 0
}

func (x *GetActionResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *GetActionResponse) GetContextUsed() map[string]*events.FeatureValue {
	if x != nil {
		return x.ContextUsed
	}
	return nil
}

var File_proto_sentinel_v1_decision_service_proto protoreflect.FileDescriptor

const file_proto_sentinel_v1_decision_service_proto_rawDesc = "" +
	"\n" +
	"(proto/sentinel/v1/decision_service.proto\x12\x14sentinel.decision.v1\x1a\x1eproto/sentinel/v1/events.proto\"\x93\x03\n" +
	"\x10GetActionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x11client_request_id\x18\x02 \x01(\tR\x0fclientRequestId\x12M\n" +
	"\acontext\x18\x03 \x03(\v23.sentinel.decision.v1.GetActionRequest.ContextEntryR\acontext\x12M\n" +
	"\aoptions\x18\x04 \x03(\v23.sentinel.decision.v1.GetActionRequest.OptionsEntryR\aoptions\x1a\\\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sentinel.events.v1.FeatureValueR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x02\n" +
	"\x11GetActionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"propensity\x18\x04 \x01(\x01R\n" +
	"propensity\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12[\n" +
	"\fcontext_used\x18\x06 \x03(\v28.sentinel.decision.v1.GetActionResponse.ContextUsedEntryR\vcontextUsed\x1a`\n" +
	"\x10ContextUsedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sentinel.events.v1.FeatureValueR\x05value:\x028\x012o\n" +
	"\x0fDecisionService\x12\\\n" +
	"\tGetAction\x12&.sentinel.decision.v1.GetActionRequest\x1a'.sentinel.decision.v1.GetActionResponseB\x1cZ\x1asentinel/proto/sentinel/v1b\x06proto3"

var (
	file_proto_sentinel_v1_decision_service_proto_rawDescOnce sync.Once
	file_proto_sentinel_v1_decision_service_proto_rawDescData []byte
)

func file_proto_sentinel_v1_decision_service_proto_rawDescGZIP() []byte {
	file_proto_sentinel_v1_decision_service_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_v1_decision_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_v1_decision_service_proto_rawDesc), len(file_proto_sentinel_v1_decision_service_proto_rawDesc)))
	})
	return file_proto_sentinel_v1_decision_service_proto_rawDescData
}

var file_proto_sentinel_v1_decision_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sentinel_v1_decision_service_proto_goTypes = []any{
	(*GetActionRequest)(nil),    // 0: sentinel.decision.v1.GetActionRequest
	(*GetActionResponse)(nil),   // 1: sentinel.decision.v1.GetActionResponse
	nil,                         // 2: sentinel.decision.v1.GetActionRequest.ContextEntry
	nil,                         // 3: sentinel.decision.v1.GetActionRequest.OptionsEntry
	nil,                         // 4: sentinel.decision.v1.GetActionResponse.ContextUsedEntry
	(*events.FeatureValue)(nil), // 5: sentinel.events.v1.FeatureValue
}
var file_proto_sentinel_v1_decision_service_proto_depIdxs = []int32{
	2, // 0: sentinel.decision.v1.GetActionRequest.context:type_name -> sentinel.decision.v1.GetActionRequest.ContextEntry
	3, // 1: sentinel.decision.v1.GetActionRequest.options:type_name -> sentinel.decision.v1.GetActionRequest.OptionsEntry
	4, // 2: sentinel.decision.v1.GetActionResponse.context_used:type_name -> sentinel.decision.v1.GetActionResponse.ContextUsedEntry
	5, // 3: sentinel.decision.v1.GetActionRequest.ContextEntry.value:type_name -> sentinel.events.v1.FeatureValue
	5, // 4: sentinel.decision.v1.GetActionResponse.ContextUsedEntry.value:type_name -> sentinel.events.v1.FeatureValue
	0, // 5: sentinel.decision.v1.DecisionService.GetAction:input_type -> sentinel.decision.v1.GetActionRequest
	1, // 6: sentinel.decision.v1.DecisionService.GetAction:output_type -> sentinel.decision.v1.GetActionResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_sentinel_v1_decision_service_proto_init() }
func file_proto_sentinel_v1_decision_service_proto_init() {
	if File_proto_sentinel_v1_decision_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_v1_decision_service_proto_rawDesc), len(file_proto_sentinel_v1_decision_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinel_v1_decision_service_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_v1_decision_service_proto_depIdxs,
		MessageInfos:      file_proto_sentinel_v1_decision_service_proto_msgTypes,
	}.Build()
	File_proto_sentinel_v1_decision_service_proto = out.File
	file_proto_sentinel_v1_decision_service_proto_goTypes = nil
	file_proto_sentinel_v1_decision_service_proto_depIdxs = nil
}
